name: personalitytest
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_analytics: ^10.9.0
  firebase_remote_config: ^4.4.0
  firebase_database: ^10.5.0
  connectivity_plus: ^5.0.2
  kakao_flutter_sdk_share: ^1.9.1
  # 웹 브라우저를 열기 위해 추가
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - res/api/mbti.json
    - res/api/test1.json
    - res/api/test2.json
